fun main(){
    println("Enter Enrollment No:")
    var no= readLine()
    println("Enter the Name:")
    var name= readLine()
    println("Enter the Branch")
    var branch= readLine()
    println("Enter the Class:")
    var class1= readLine()
    println("Enter the Batch:")
    var batch= readLine()
    println("Enter the College Name:")
    var clg= readLine()
    println("Enter the University:")
    var uni= readLine()
    println("Enter the age:")
    var age= readLine()
    println("Students Data:")
    println("Enrollment No:$no")
    println("Name is:$name")
    println("Branch is:$branch")
    println("Class is:$class1")
    println("Batch is:$batch")
    println("College is:$clg")
    println("University is:$uni")
    println("Age is:$age")}
